// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPQv5cbxlgigmK6jy8G-R9GzCe1SqNh7g',
    appId: '1:939766273096:web:d310da04186af2823c347d',
    messagingSenderId: '939766273096',
    projectId: 'sample-classrooms',
    authDomain: 'sample-classrooms.firebaseapp.com',
    storageBucket: 'sample-classrooms.firebasestorage.app',
    measurementId: 'G-TLVYYKHJEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFKiCtJBT_jd_65LL48ETgNZUvjGTskoM',
    appId: '1:939766273096:android:39662d00d24a9c7a3c347d',
    messagingSenderId: '939766273096',
    projectId: 'sample-classrooms',
    storageBucket: 'sample-classrooms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBNF8vqojlFFOQrqLVXG0gZpD1laXFuug',
    appId: '1:939766273096:ios:6e55e0f7095883263c347d',
    messagingSenderId: '939766273096',
    projectId: 'sample-classrooms',
    storageBucket: 'sample-classrooms.firebasestorage.app',
    iosBundleId: 'com.example.sampleClassroom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPQv5cbxlgigmK6jy8G-R9GzCe1SqNh7g',
    appId: '1:939766273096:web:e4c02da4f169d4073c347d',
    messagingSenderId: '939766273096',
    projectId: 'sample-classrooms',
    authDomain: 'sample-classrooms.firebaseapp.com',
    storageBucket: 'sample-classrooms.firebasestorage.app',
    measurementId: 'G-RF1GMSEDR9',
  );

}